import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
import Link from 'next/link';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning prevents mismatch from extension-injected attrs */}
      <body suppressHydrationWarning>
        <nav>
          <Link href="/">/</Link> | <Link href="/book-ex">/book-ex</Link> | <Link href="/auth-ex">/auth-ex</Link> | <Link href="/orders-ex">/orders-ex</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}


